### PR TITLE
Dynamic Parameters Only validating params that are part of the plugin

### LINKED ISSUE #5100: Bug in parameter configuration in controller.
I think I have found a bug related to parameter configuration in the controller. 

I started the robot as usual this morning and it gave me this configuration error on startup.

Image

It says that ``The value of parameter 'MPPI.vx_min' is incorrectly set to -0.350000, it should be >=0. Ignoring parameter update.``.

I looked at the documentation and this is the  default value: https://docs.nav2.org/configuration/packages/configuring-mppic.html

I also looked at this part of the code and I found it in the RPP controller!!! 

https://github.com/ros-navigation/navigation2/blob/5423eba732ed16b4f97a7353027c1f444b6edc60/nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp#L230-L234

Maybe this is related to this PR #4971

### PR DESCRIPTION
**Pull request by Nils-ChristianIseke**
Fixing a bug introduced in  #4971.
Should fix #5100.

### CODE REVIEW

**Comment by Nils-ChristianIseke** [comment]
> This PR addresses this [issue](https://github.com/ros-navigation/navigation2/issues/5100), right?

Yes. I  haven't tested it yet! Will hopefully do so tomorrow. If you have time to test it i would appreciate it :).

File: nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp [hunk 1]
```diff
@@ -226,7 +226,7 @@ rcl_interfaces::msg::SetParametersResult ParameterHandler::validateParameterUpda
         logger_, "The value inflation_cost_scaling_factor is incorrectly set, "
         "it should be >0. Ignoring parameter update.");
         result.successful = false;
-      } else if (parameter.as_double() < 0.0) {
+      } else if (name.find(plugin_name_ + ".") == 0 && parameter.as_double() < 0.0) {
```
Comment (SteveMacenski) [inline nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp:229]: I think as a more general purpose solution to apply to other nodes, we should check this in L222 after we get the `type` and `name` to see if the `name` is part of our node. If not, `continue;` onto the next parameter and simply bypass these checks entirely.

**Review by SteveMacenski — CHANGES_REQUESTED** [review]

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@Nils-ChristianIseke approved - can you do this for all controllers?

**Comment by Nils-ChristianIseke** [comment]
@SteveMacenski do you want me to do this in this PR?

**Comment by SteveMacenski** [comment]
Yes please - so we resolve the scope of the ticket. I think there's one callout that should also be made: `controller_frequency`. This is sometimes used in the controllers and obtained by the main Controller Server which is dynamically reconfigurable. If this parameter is changed, then I think we should trigger the update as well. Its used in virtually all of the controllers (DWB, MPPI, RPP, Rotation Shim). it actually looks like RPP needs to have `controller_frequency` checked and updated in the dynamic parameter callback. Right now it doesn't update. 

The other option would be to remove this as a dynamic parameter option. Which... seems reasonable

File: nav2_controller/plugins/simple_goal_checker.cpp [hunk 2]
```diff
@@ -145,18 +145,18 @@ SimpleGoalChecker::dynamicParametersCallback(std::vector<rclcpp::Parameter> para
 {
   rcl_interfaces::msg::SetParametersResult result;
   for (auto & parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_controller/plugins/simple_goal_checker.cpp:150]: Didn't add the `param_name.find(plugin_name_ + ".") != ` line?

File: nav2_theta_star_planner/src/theta_star_planner.cpp [hunk 3]
```diff
@@ -238,26 +238,26 @@ ThetaStarPlanner::dynamicParametersCallback(std::vector<rclcpp::Parameter> param
 {
   rcl_interfaces::msg::SetParametersResult result;
   for (auto parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_theta_star_planner/src/theta_star_planner.cpp:243]: No `param_name.find(plugin_name_ + ".") != ` check?

File: nav2_smac_planner/src/smac_planner_lattice.cpp [hunk 4]
```diff
@@ -476,66 +476,66 @@ SmacPlannerLattice::dynamicParametersCallback(std::vector<rclcpp::Parameter> par
   bool reinit_smoother = false;
 
   for (auto parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_smac_planner/src/smac_planner_lattice.cpp:481]: No `param_name.find(plugin_name_ + ".") != ` check?

File: nav2_smac_planner/src/smac_planner_hybrid.cpp [hunk 5]
```diff
@@ -581,29 +581,29 @@ SmacPlannerHybrid::dynamicParametersCallback(std::vector<rclcpp::Parameter> para
...
-      } else if (name == _name + ".analytic_expansion_max_length") {
+      } else if (param_name == _name + ".analytic_expansion_max_length") {
         reinit_a_star = true;
         _search_info.analytic_expansion_max_length =
           static_cast<float>(parameter.as_double()) / _costmap->getResolution();
-      } else if (name == _name + ".analytic_expansion_max_cost") {
+      } else if (param_name == _name + ".analytic_expansion_max_cost") {
         reinit_a_star = true;
         _search_info.analytic_expansion_max_cost = static_cast<float>(parameter.as_double());
-      } else if (name == "resolution") {
```
Comment (SteveMacenski) [inline nav2_smac_planner/src/smac_planner_hybrid.cpp:606]: This file doesn't have the `param_name.find(plugin_name_ + ".") != ` check because of this, right?

File: nav2_smac_planner/src/smac_planner_2d.cpp [hunk 6]
```diff
@@ -362,34 +362,34 @@ SmacPlanner2D::dynamicParametersCallback(std::vector<rclcpp::Parameter> paramete
   bool reinit_downsampler = false;
 
   for (auto parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_smac_planner/src/smac_planner_2d.cpp:366]: No `param_name.find(plugin_name_ + ".") != ` check?

File: nav2_navfn_planner/src/navfn_planner.cpp [hunk 7]
```diff
@@ -525,19 +525,19 @@ NavfnPlanner::dynamicParametersCallback(std::vector<rclcpp::Parameter> parameter
 {
   rcl_interfaces::msg::SetParametersResult result;
   for (auto parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_navfn_planner/src/navfn_planner.cpp:530]: No `param_name.find(plugin_name_ + ".") != ` check?

File: nav2_planner/src/planner_server.cpp [hunk 8]
```diff
@@ -730,11 +730,11 @@ PlannerServer::dynamicParametersCallback(std::vector<rclcpp::Parameter> paramete
   std::lock_guard<std::mutex> lock(dynamic_params_lock_);
   rcl_interfaces::msg::SetParametersResult result;
   for (auto parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_planner/src/planner_server.cpp:735]: Can we apply the inverse like we do in the Controller Server's callback?

File: nav2_docking/opennav_docking/src/controller.cpp [hunk 9]
```diff
@@ -208,31 +208,31 @@ Controller::dynamicParametersCallback(std::vector<rclcpp::Parameter> parameters)
 
   rcl_interfaces::msg::SetParametersResult result;
   for (auto parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_docking/opennav_docking/src/controller.cpp:213]: This can check for `controller.` in the name to use, right?

File: nav2_costmap_2d/src/costmap_2d_ros.cpp [hunk 10]
```diff
@@ -723,42 +723,42 @@ Costmap2DROS::dynamicParametersCallback(std::vector<rclcpp::Parameter> parameter
   std::lock_guard<std::mutex> lock_reinit(_dynamic_parameter_mutex);
 
   for (auto parameter : parameters) {
-    const auto & type = parameter.get_type();
-    const auto & name = parameter.get_name();
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
```
Comment (SteveMacenski) [inline nav2_costmap_2d/src/costmap_2d_ros.cpp:727]: We can skip like the Controller server if there's any `.`'s right?

**Review by SteveMacenski — CHANGES_REQUESTED** [review]
What about MPPI? 

Overall looks good, I want this in for Kilted release so I'm going to block forking Kilted until we can get this in, I think its important. Thanks for this great work!

**Comment by Nils-ChristianIseke** [comment]
@SteveMacenski you are too quick with your reviews ;). I will ping you as soon this one is review ready :). Will hopefully find some time today to finish it!

**Comment by SteveMacenski** [comment]
OK :-) Let me know

File: nav2_controller/src/controller_server.cpp [hunk 11]
```diff
@@ -860,9 +860,7 @@ ControllerServer::dynamicParametersCallback(std::vector<rclcpp::Parameter> param
     }
 
     if (param_type == ParameterType::PARAMETER_DOUBLE) {
-      if (param_name == "controller_frequency") {
```
Comment (Nils-ChristianIseke) [inline nav2_controller/src/controller_server.cpp]: This commit aims to remove the controller_frequency as dynamic parameter. Not sure if i missed something?

**Comment by Nils-ChristianIseke** [comment]
@SteveMacenski still need to look into mppi and the possible parameter overlap, but you can have a look a the rest. (Did not run test locally as building took to long :D). I will not finish this today, fell free to take over if you are in a rush.

**Comment by Nils-ChristianIseke** [comment]
> What about MPPI?

As far as i get it this is  already covered  in the [param handler of mppi ](https://github.com/ros-navigation/navigation2/blob/de9609828355e485d43138014bc29227bea5102c/nav2_mppi_controller/src/parameters_handler.cpp#L68)

File: nav2_smac_planner/src/smac_planner_hybrid.cpp (hunk 5 above)
Comment (Nils-ChristianIseke) [reply nav2_smac_planner/src/smac_planner_hybrid.cpp:639]: Added the check with allowing param_name resolution

**Comment by Nils-ChristianIseke** [comment]
> What about MPPI?
Not sure what to do there / what's the issue.

**Comment by SteveMacenski** [comment]
I'll wait until your word - let me know :-)

**Comment by Nils-ChristianIseke** [comment]
@SteveMacenski I think i need some feedback regarding the changes necessary to nav2_mppi_controller. Could you have a look at https://github.com/ros-navigation/navigation2/pull/5106/commits/15ed1c995162f14e235b2eb4893cf3a4fa483d28? Not sure if i am heading in the right direction there.

**Comment by Nils-ChristianIseke** [comment]
@SteveMacenski CircleCI was [failing](https://app.circleci.com/jobs/github/ros-navigation/navigation2/43387)  for https://github.com/ros-navigation/navigation2/pull/5106/commits/9e2655be822f569b8e3e4f97185e1b348eaf2c7a and than turned green the next time without me changing the failing package. Maybe there is a flaky test?

**Comment by SteveMacenski** [comment]
It looks to be a little flaky, something happened in the last ~2 weeks or so that introduced flakiness. I suspect some regressions in rclcpp from the rush to get out Kilted (or hey, could be me too!) but I haven't had the cycles yet to investigate.

**Review by SteveMacenski — COMMENTED** [review]
A couple of small cleanups but LGTM!

File: nav2_mppi_controller/src/parameters_handler.cpp [hunk 12]
```diff
@@ -57,25 +58,31 @@ ParametersHandler::dynamicParamsCallback(
...
+      if (auto callback = get_param_callbacks_.find(param_name);
+        callback != get_param_callbacks_.end())
+      {
+        callback->second(param, result);
+      }
+    }
+    for (auto & post_cb : post_callbacks_) {
+      post_cb();
+    }
   }
```
Comment (SteveMacenski) [inline nav2_mppi_controller/src/parameters_handler.cpp:85]:
```suggestion
  }

```

File: nav2_mppi_controller/src/parameters_handler.cpp [hunk 13]
```diff
@@ -57,25 +58,31 @@ ParametersHandler::dynamicParamsCallback(
...
-    if (auto callback = get_param_callbacks_.find(param_name);
-      callback != get_param_callbacks_.end())
-    {
-      callback->second(param, result);
+    if (param_name.find(name_ + ".") != 0) {
+      continue;
     }
+    plugin_params.push_back(param);
   }
+  if (!plugin_params.empty()) {
```
Comment (SteveMacenski) [inline nav2_mppi_controller/src/parameters_handler.cpp:69]:
```suggestion

  if (!plugin_params.empty()) {
```

File: nav2_mppi_controller/src/parameters_handler.cpp [hunk 14]
```diff
@@ -57,25 +58,31 @@ ParametersHandler::dynamicParamsCallback(
...
-    post_cb();
+    for (auto & param : plugin_params) {
+      const std::string & param_name = param.get_name();
+      if (auto callback = get_param_callbacks_.find(param_name);
+        callback != get_param_callbacks_.end())
+      {
+        callback->second(param, result);
+      }
+    }
+    for (auto & post_cb : post_callbacks_) {
```
Comment (SteveMacenski) [inline nav2_mppi_controller/src/parameters_handler.cpp:82]:
```suggestion

    for (auto & post_cb : post_callbacks_) {
```

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Docs https://github.com/ros-navigation/docs.nav2.org/pull/699

File: nav2_mppi_controller/test/parameter_handler_test.cpp [hunk 15]
```diff
@@ -117,40 +119,42 @@ TEST(ParameterHandlerTest, PrePostDynamicCallbackTest)
 TEST(ParameterHandlerTest, GetSystemParamsTest)
 {
   auto node = std::make_shared<rclcpp_lifecycle::LifecycleNode>("my_node");
-  node->declare_parameter("param1", rclcpp::ParameterValue(true));
-  node->declare_parameter("ns.param2", rclcpp::ParameterValue(7));
+  node->declare_parameter("test.param1", rclcpp::ParameterValue(true));
+  node->declare_parameter("ns.test.param2", rclcpp::ParameterValue(7));
```
Comment (Nils-ChristianIseke) [inline nav2_mppi_controller/test/parameter_handler_test.cpp:123]: @SteveMacenski it just came to my mind that using ns here is conflicting with our check in the dynamic params update?

Comment (SteveMacenski) [reply nav2_mppi_controller/test/parameter_handler_test.cpp:123]: Can you be more specific? I thought I understood what you meant a couple of times and each time I wrote up a comment back I realized looking at the tests / code that that wasn't what was happening :laughing: So I suppose its time for clarification hah.

Comment (Nils-ChristianIseke) [reply nav2_mppi_controller/test/parameter_handler_test.cpp:123]: Thanks for pointing that out! I’ll work on improving my communication 😊

I was confused by the changes i made to this test. Calling getParameters("ns") instead of getParameters("test"). getParameters("ns")  is imo implicitly suggesting that we would allow an additional custom namespace. Fixed this in https://github.com/ros-navigation/navigation2/pull/5190.
