### PR TITLE
MPPI: add arc-length path progress to fix path skipping on curved paths

### LINKED ISSUE #5925: [MPPI] Path tracking in U-turns
**Required Info:**

- Operating System:
  - Ubuntu 24.04
- Computer:
  - i7-13850HX Laptop
- ROS2 Version:
  - Jazzy binaries
- Version or commit hash:
  - ros-jazzy-navigation2	1.3.8-1noble.20250915.220228
- DDS implementation:
  - Default (rmw_fastrtps_cpp)
- Nav2 Package:
  - nav2_mppi_controller 

I’m wondering whether an alternative implementation of FurthestReachedPoint() would be interesting or worth considering. If it’s useful, I’d be happy to contribute a PR.

I’d really appreciate your input on this. I may be overlooking something in my setup, so I want to make sure I’m not misattributing the issue. Any pointers on where to look would be greatly appreciated.

### Details
My application requires coverage of an area, tight path tracking, and dynamic obstacle avoidance. 

#### Steps to reproduce issue
Send a path to MPPI with a "tight" U-Turn (e.g. 0.6 m)

#### Expected behavior
MPPI's optimal trajectory closely follows the path sent. 

#### Actual behavior
When approaching the U-Turn, MPPI's optimal trajectory leans towards the end of the "pruned path" (videos below).

#### Additional information
My understanding is that this is caused by the interaction of:
- `findPathFurthestReachedPoint()` (in `include/nav2_mppi_controller/tools/utils.hpp`)

With my nav config:
- Long "prediction horizon" ( `time_steps * model_dt` = `80 * 0.1` = 8 secs)
- Long prune_distance (5 meters)

Given the way `FurthestReachedPoint()` works, the end point of some of the "sampled control sequences" will effectively be on the "way back" of the U-Turn, so the selected point will already be on the way back, instead of continuing following the path.

Reducing `prune_distance` (and time_steps) would help; however, that would affect the obstacle avoidance capabilities (not long enough horizon time to result in control_sequences that make progress while avoiding obstacles). 
Note: In my system, once the coverage path is calculated, it is sent to the controller (MPPI), which is responsible for dynamic obstacle avoidance (also static obstacles that were not in the costmap when the coverage path was computed).

#### Controller config (main params):
```
    # MPPI plugin configuration
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 80
      model_dt: 0.1
      batch_size: 1200
      vx_std: 0.25
      vy_std: 0.0
      wz_std: 0.35
      vx_max: 0.5
      vx_min: -0.4
      vy_max: 0.5
      wz_max: 0.50 
      ax_max: 0.625     
      ax_min: -0.40   
      az_max: 1.0
      iteration_count: 1
      prune_distance: 5.0
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      ...
      critics: ["ConstraintCritic", "GoalAngleCritic", "GoalCritic", "ObstaclesCritic", "PathAlignCritic", "PathAngleCritic", "PathFollowCritic", "PreferForwardCritic", "VelocityDeadbandCritic"]

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        max_path_occupancy_ratio: 0.02
        use_path_orientations: false
        trajectory_point_step: 2
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0 
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 2
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0 
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      ...
      [other critics]
      ...

```

#### Videos: 

https://github.com/user-attachments/assets/0a77d41a-d86a-4d83-a7fb-f16c45354183

https://github.com/user-attachments/assets/c25552f4-39b7-4d13-9247-560988bb9299

### PR DESCRIPTION
**Pull request by CarlosHdezM**
Improves `findPathFurthestReachedPoint` by bounding the Euclidean search region to the candidate trajectory arc-length. Prevents the Euclidean nearest-point match from jumping ahead on curved paths (e.g. U-turns).

Relates to #5925

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here  #5925) |
| Primary OS tested on | Ubuntu 24.04 |
| Robotic platform tested on | Gazebo simulation of Turtlebot3 |
| Does this PR contain AI generated software? | No |
| Was this PR description generated by AI software? |No |

---

## Description of contribution in a few bullet points

* `findPathFurthestReachedPoint` now bounds the Euclidean nearest-point
  match with the trajectory's total arc-length, preventing jumps to distant path
  segments brought spatially close by path curvature (e.g. U-turns)

## Description of documentation updates required from your changes

* No new params introduced

## Description of how this change was tested

* Existing unit tests pass 
* Linting validated with `colcon test` (cpplint + uncrustify)
* Added unit test 
* Tested on simulation of diff robot (Turtlebot 3), as well as simulated and real tricycle robot.

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists
- [ ] Should this be backported to current distributions? If so, tag with `backport-*`.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@mini-1235 if you wanted to take a look at something, a review and testing here would be helpful!

**Comment by mini-1235** [comment]
> @mini-1235 if you wanted to take a look at something, a review and testing here would be helpful!

Ok, I can take a look on Friday

**Comment by CarlosHdezM** [comment]
> Ok, I can take a look on Friday

Hi @mini-1235 , on Saturday evening I can make a push with a scenario that makes evident the issue we are trying to address here. On #5925 there are some videos that show it, but would it be useful for you if I sent you how to reproduce yourself?

**Comment by mini-1235** [comment]
> but would it be useful for you if I sent you how to reproduce yourself?

Yes, that would be very helpful! I haven't gone through the discussion in #5925 yet, so any reproduction steps you can share to help me better understand the issue would be greatly appreciated :smile:

**Comment by CarlosHdezM** [comment]
@mini-1235 

When you have time, I think it will be quite useful to go through #5925 :) 
Overall, the discussion is about how the current implementation of findPathFurthestReachedPoint() behaves "not so nicely" in scenarios such as U-turns, due to the Euclidean-distance point-to-path matching alone. I'm proposing a method that combines the Euclidean matching with trajectory's arc-length matching. 


Let me proceed to provide the steps to reproduce these scenarios:

NOTE: `use_arc_length_path_progress` **OFF** uses the current implementation. **ON** the proposed method. All the videos show first OFF and then ON.

https://github.com/user-attachments/assets/bc0beb75-6440-41e1-900b-81bacd6b5084



https://github.com/user-attachments/assets/997ecd57-1498-4721-87ab-1a0459959bcd



https://github.com/user-attachments/assets/e161ffbd-053a-4a74-9cc1-50b7b46c6ddf

**Comment by CarlosHdezM** [comment]
>Let me proceed to provide the steps to reproduce these scenarios:

Basically, the easiest way to see how this issue happens, is when the "exploration space" of the sampled trajectories is bigger (more time_steps, prune_distance, vx_std, wz_std), which in fact is needed for certain applications such as larger robots that need to do bigger obstacle avoidance. 

On my Nav2's fork, I created a separate branch [reproduce-issue-5925-mppi-uturn-path-tracking](https://github.com/CarlosHdezM/navigation2/tree/reproduce-issue-5925-mppi-uturn-path-tracking), just for trying things out:
- It is based on this PR branch
- It merges #6050 to be able to visualize the "furthest reached point" on RVIZ
- It adds a very simple package to send some "hardcoded" paths 
- It modifies the MPPI params just to increase the exploration space. The rest of the params (e.g. Critics are the default ones)
- It disables `use_localization` in tb3_simulation_launch.py‎ (I'm running the "empty world", so I publish the map -> identity tf.

So, feel free to use that branch to reproduce the issue more quickly.

```bash
ros2 run tf2_ros static_transform_publisher --frame-id map --child-frame-id odom

ros2 launch nav2_bringup tb3_simulation_launch.py headless:=True world:=$(ros2 pkg prefix nav2_minimal_tb3_sim)/share/nav2_minimal_tb3_sim/worlds/tb3_empty_world.sdf.xacro
```

Finally, you can send some of the u-turn paths, like:

```bash
ros2 run test_nav2_controller send_follow_path_map --ros-args -p path:=left_uturn_0-6m.json -p use_sim_time:=true
```

In rviz, could be helpful to add:
Add a PointStamped subscribing to /controller_server/furthest_reached_point
Add a Path subscribing to /controller_server/optimal_path

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp [hunk 1]
```diff
@@ -318,6 +318,89 @@ inline size_t findPathFurthestReachedPoint(const CriticData & data)
...
+  const size_t n_rows = static_cast<size_t>(traj_x_end.rows());
+  const size_t n_cols = data.path.x.size();
+  int max_id_by_trajectories = 0;
+
+  // Pre-compute cumulative arc-lengths along the reference path.
+  std::vector<float> path_arc(n_cols, 0.0f);
+  for (size_t i = 1; i < n_cols; ++i) {
+    const float dx = data.path.x(i) - data.path.x(i - 1);
+    const float dy = data.path.y(i) - data.path.y(i - 1);
+    path_arc[i] = path_arc[i - 1] + sqrtf(dx * dx + dy * dy);
```
Comment (adivardi) [inline nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: I think you should cache this. Put it in another function `computePathIntegratedArcLength` plus another `setPathIntegratedPathLengthIfNotSet`.
If you check, this is the same computation done in `path_align_critic`. so if you cache it, it will only be done once.

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp [hunk 2]
```diff
@@ -318,6 +318,89 @@ inline size_t findPathFurthestReachedPoint(const CriticData & data)
...
 }
 
+/**
+ * @brief Arc-length furthest-point method. Bounds the Euclidean nearest-point
+ * match with the trajectory's arc-length to prevent jumping to a distant path
+ * segment brought spatially close by path curvature (e.g. a U-turn).
+ * @param data Data to use
+ * @return Idx of furthest path point reached by a set of trajectories
+ */
+inline size_t findPathFurthestReachedPointArcLength(const CriticData & data)
```
Comment (SteveMacenski) [inline nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: Needs unit test coverage, CI tells me this is actually never called.

File: nav2_bringup/params/nav2_params.yaml [hunk 3]
```diff
@@ -150,6 +150,7 @@ controller_server:
       iteration_count: 1
       temperature: 0.3
       gamma: 0.015
+      use_arc_length_path_progress: false
```
Comment (SteveMacenski) [inline nav2_bringup/params/nav2_params.yaml]: For here and other uses in variables: I think we should brainstorm some better names. I read this and even after reading the PR its not immediately clear to me.

I might also argue that we should only include this feature if it globally fixes an issue and does not have any downsides / edge cases which it does not properly handle / fallback to current behavior. Thus does not need to be parameterized, its always on.

The difference between one robot and another is not important for configuring a setting like this - the robots should be capable of all commands given to it, so this really isn't a 'tuning' thing. Either it fixes a problem and doesn't introduce new ones, or it doesn't.

Does that make sense? 

So any edge cases where this causes issues? Are there discontinuities in the arc-based furthest path point detected? Does it essentially become the Euclidean version in straight and broadly-straight paths? 

Might be worth putting together a broad set of generated paths / curves and checking the selection and behavior is good. Straight, through some turns of increasing length (longer turn) / sharpness (radius), and maybe a couple of example "S" curves like when weaving in the Tb4 sandbox world for good measure final test. Make sure the behavior is reasonable, no crazy  non-productive slow down on the turns, etc. Claude Code is your friend here to auto generate paths and iterate through a few of them using the loopback simulator. 

> Add a dedicated correctness unit test for the arc-length method with a U-turn geometry (verifying it returns a lower index than Euclidean)
 
A good TODO in that front as well.

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp [hunk 4]
```diff
@@ -318,6 +318,89 @@ inline size_t findPathFurthestReachedPoint(const CriticData & data)
...
+
+  // Pre-compute cumulative arc-lengths along the reference path.
+  std::vector<float> path_arc(n_cols, 0.0f);
+  for (size_t i = 1; i < n_cols; ++i) {
+    const float dx = data.path.x(i) - data.path.x(i - 1);
+    const float dy = data.path.y(i) - data.path.y(i - 1);
+    path_arc[i] = path_arc[i - 1] + sqrtf(dx * dx + dy * dy);
+  }
+
+  // Vectorized arc-length computation for all trajectories at once.
```
Comment (SteveMacenski) [inline nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: Note that the for;for loop in the other Euclidean implementation actually was faster than the Eigenized version. Did you test a more basic version just doing the `for` loop to compute the integrated distance within the `for(i)` loop?

Comment (SteveMacenski) [reply nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: Is there another place in the code we do a for each sample loop that we can cache this information as well so its already available? 

I'm thinking maybe the state, given it has the positions, velocities, I suppose adding a ` Eigen::ArrayXf integrated_traj_distances` wouldn't be crazy and may be useful in other critics like path align or follow. 

This is an advanced topic, I'd start with the for;for instead of the Eigen `traj_arcs` to see if that's actually better performance or not. Eeking out those few nanoseconds is important in this part of the code, I believe

**Review by SteveMacenski — COMMENTED** [review]
On your videos for "OFF" how is the robot bounded to the path so that even though the optimal trajectory is trying to get it to move off, its not? 

Also you forgot the "ON" video :wink:

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp (hunk 4 above)
Comment (SteveMacenski) [reply nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: Also maybe try this after validating its correct. Take it with the massive grain of salt that it comes from Claude with some human tweaks by yours truly. I did sanity check it at a high level that it seems to match your logic, but I also didn't really validate your logic much more than on a conceptual level :-) 

```
inline size_t findPathFurthestReachedPointArcLength(const CriticData & data)
{
  const int traj_cols = data.trajectories.x.cols();
  const int n_rows = static_cast<int>(data.trajectories.x.rows());
  const int n_cols = static_cast<int>(data.path.x.size());

  const Eigen::ArrayXf seg_lens =
    ((data.path.x.tail(n_cols - 1) - data.path.x.head(n_cols - 1)).square() +
     (data.path.y.tail(n_cols - 1) - data.path.y.head(n_cols - 1)).square()).sqrt();
  std::vector<float> path_arc(n_cols, 0.0f);
  for (int i = 1; i < n_cols; ++i) {
    path_arc[i] = path_arc[i - 1] + seg_lens(i - 1);
  }

  const Eigen::ArrayXf traj_arcs =
    ((data.trajectories.x.rightCols(traj_cols - 1) - data.trajectories.x.leftCols(traj_cols - 1)).square() +
     (data.trajectories.y.rightCols(traj_cols - 1) - data.trajectories.y.leftCols(traj_cols - 1)).square())
    .sqrt().rowwise().sum();

  const auto & traj_x_end = data.trajectories.x.col(traj_cols - 1);
  const auto & traj_y_end = data.trajectories.y.col(traj_cols - 1);

  int max_id = 0;
  for (int i = 0; i < n_rows; ++i) {
    Eigen::Index eucl_idx;
    ((data.path.x - traj_x_end(i)).square() +
     (data.path.y - traj_y_end(i)).square()).minCoeff(&eucl_idx);

    int integ_idx = static_cast<int>(
      std::lower_bound(path_arc.begin(), path_arc.end(), traj_arcs(i)) - path_arc.begin());
    integ_idx = std::min(integ_idx, n_cols - 1);

    max_id = std::max(max_id, std::min(static_cast<int>(eucl_idx), integ_idx));
    if (max_id == n_cols - 1) break;
  }

  return static_cast<size_t>(max_id);
}
```

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp (hunk 1 above)
Comment (CarlosHdezM) [reply nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: Yes, I agree that this is a very good idea. I didn't jump into implementing that yet for this draft PR, as I wanted to get initial validation of a less "intrusive" approach. But yes, I will experiment as it's definitely worth it looking into it =)

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp (hunk 2 above)
Comment (CarlosHdezM) [reply nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: I wanted to get a first opinion first. It looks that we are moving in the right direction (?), so  I will proceed to add them later =)

> Also you forgot the "ON" video 😉

Oops, my bad. I was juggling with OBS with the "record" and "pause" options, and I just got it wrong. I will re-record them and show them here.

> On your videos for "OFF" how is the robot bounded to the path so that even though the optimal trajectory is trying to get it to move off, its not?

I didn't add any "special" or "particular" bounding to the path. My setup (as shown in branch [reproduce-issue-5925-mppi-uturn-path-tracking](https://github.com/CarlosHdezM/navigation2/tree/reproduce-issue-5925-mppi-uturn-path-tracking)) only touches `prune_distance`, `time_steps`, `vx_std`, `wz_std`, `vx_max`. The videos in "OFF" use the current implementation.

**Review by mini-1235 — COMMENTED** [review]
Hi, I cherry-picked the commit in this PR and tested them on tight u-turn scenarios (e.g. using similar poses for both the start and goal) yesterday and today. The behavior is definitely improved compared to before! I remember that I had to tune the prune_distance in the path handler to get better performance in these cases, so this is a great addition.

Not to block this PR, but I am also wondering if this issue could be addressed at the path handler level, since other controllers might encounter similar problems. A couple of ideas that I had in my mind:
- Similar to how cusps are handled, we could prune the path up to the u-turn point and then unlock it once the robot gets close https://github.com/ros-navigation/navigation2/blob/826f1d527a46088e03215b0becbd9e6f659520c4/nav2_controller/plugins/feasible_path_handler.cpp#L243
- Introduce dynamic pruning distance, similar to what is proposed here:  https://github.com/ros-navigation/navigation2/issues/1664, I tried this a few weeks ago, but haven't had a robust solution at the moment

**Comment by SteveMacenski** [comment]
Both are interesting ideas, but both I think would be hard to perfect edge cases. Maybe worth experimenting with! 

But I agree that we shouldn't block this PR in particular. 

What's this is doing mostly is just using integrated path distances rather than L2 distances. I believe RPP already does that. Graceful I'm not 100% sure. So I think with MPPI our bases should be covered. https://github.com/ros-navigation/navigation2/blob/8c4051dd2315631e9db680400802f58652afb1c5/nav2_util/src/controller_utils.cpp#L92

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp (hunk 2 above)
Comment (CarlosHdezM) [reply nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: Hi @SteveMacenski, sorry I haven't replied to all the comments yet. I'm addressing everything as fast as I can :)

For the moment, I have updated my comment by adding the correct videos (showing the "ON" part as well).

You can see how for "sharp" U-turns (like 0.2m radius U-turn), it still struggles, although the behavior is better in general. It's better, but not perfect. It's also worth mentioning again that this is using the default critic settings

**Comment by adivardi** [comment]
I tested this a bit more and it works quite nicely! It definetely improves the results when:
- approaching a u-turn: solution no longer jumping
- obstacle before or in the u-turn: 
	- robot no longer does a huge shortcut and get stuck, but tries to comeback to the u-turn when possible
- obstacle in serpentines: previously, when the robot returned to path before a u-turn after an obstacle, the FurthestReachedPoint will jump to the next serpentine line (because robot is at an angle with the current path => straight trajectories reach the next line). This lead to the robot trying to shorcut really early and then "changing its mind" leading to weird trajectories.  With this change the shortcutting is gone and results are much better.

File: nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp (hunk 2 above)
Comment (SteveMacenski) [reply nav2_mppi_controller/include/nav2_mppi_controller/tools/utils.hpp]: No worries, let me know in a comment when you want me to take a look again!

**Comment by CarlosHdezM** [comment]
Hi @SteveMacenski, @mini-1235, @adivardi  — thank you all for the thorough review. I've been working through the major discussion points and wanted to consolidate everything into a single update rather than scatter replies. Here is where things stand. It's overall 5 points:

1. Removing the `use_arc_length_path_progress` parameter
2. Eigen vs scalar for the trajectory arc-length computation
3. Refactoring `findPathFurthestReachedPointArcLength` following Steve's snippet
4. Caching `path_integrated_distances`
5. Summary: Action Items

**Comment by CarlosHdezM** [comment]
## 1. Removing the `use_arc_length_path_progress` parameter

> _"I might also argue that we should only include this feature if it globally fixes an issue and does not have any downsides / edge cases which it does not properly handle / fallback to current behavior. Thus does not need to be parameterized, its always on."_
> — @SteveMacenski

I agree, and I am proposing to **remove the `use_arc_length_path_progress` parameter entirely** and let this be the sole implementation. The rationale follows.

### Why the arc-length bound is physically sound and always safe

The method's key property — which I want to be explicit about — is that it is a strict upper-bound **added on top of Euclidean matching, not a replacement**. Concretely:

```
final_idx = max over all trajectories of  min(eucl_idx, integ_idx)
```

The physical justification for the bound is: a trajectory whose sampled arc-length is L metres cannot physically have carried the robot more than L metres along the reference path. If the Euclidean match returns an index that would require the robot to have covered more path distance than the trajectory's physical length allows, that match is a geometric ambiguity caused by path curvature bringing distant path segments spatially close (the U-turn case). The arc-length bound catches exactly this scenario and nothing else.

On **broadly straight paths, curves, arcs** the two bounds nearly coincide and the clamp never activates. The method reduces exactly to Euclidean with no overhead other than the computation of the bound itself.

### Testing

I tested extensively with different path shapes and confirmed the behavior:

- **Straight**, **Gentle arcs**, **S-curves**  paths: behaviour identical to Euclidean ✓ -> no "discontinuities/jumps"; the furthest point progresses monotonically as the robot moves ✓
- **U-turns (0.2 m, 0.4 m, 0.6 m radius)**: the key fix — the clamp prevents the furthest point from jumping to the far leg of the turn ✓
- **U-turns with obstacles before/in the turn**: @adivardi confirmed the robot no longer does a huge shortcut and gets stuck ✓
- **Serpentines** (adjacent parallel segments): @adivardi confirmed the fix eliminates the jump to the next serpentine line ✓

No scenario was found where the arc-length bound produces worse behaviour than Euclidean.


### Implementation consequence: merging back to one function

With the parameter removed, `findPathFurthestReachedPointEuclidean` and `findPathFurthestReachedPointArcLength` collapse back into a single `findPathFurthestReachedPoint` — exactly the pre-PR structure, with the Euclidean inner loop replaced by the Euclidean + arc-length bounded version. This also eliminates all the `use_arc_length_path_progress` references in `critic_data.hpp`, `optimizer_settings.hpp`, `optimizer.cpp`, and `nav2_params.yaml`.

**Comment by CarlosHdezM** [comment]
## 2. Eigen vs scalar for the trajectory arc-length computation

> _"Note that the for;for loop in the other Euclidean implementation actually was faster than the Eigenized version. Did you test a more basic version just doing the for loop to compute the integrated distance within the for(i) loop?"_
> — @SteveMacenski

I implemented and benchmarked two variants back-to-back on the same data:

- **Eigen** (current): `traj_arcs` computed upfront for all trajectories at once using Eigen matrix expressions, then scalar Euclidean inner loop per trajectory.
- **Scalar**: trajectory arc-length accumulated inside the outer `for(i)` loop using `data.trajectories.x(i, k)` — fully scalar, no Eigen for the traj part.

8 scenarios were tested covering typical deployment configs, including the two I care most about:

```
Scenario |batch steps path |   Eig µs    Scl µs 
-----------------------------------------------------------------------------------
1 |       1000    56  100 |      102.5   131.9 
2 |       2000    56  140 |      275.5   337.2 
3 |       2000    80  200 |      395.9   513.8 
4 |        500    30   60 |       28.9    37.0 
5 |       2000   100  300 |      593.3   732.3 
6 |       1000    56  500 |      459.8   501.1 
7 |       2000    56   60 |      124.2   199.5 
8 |        500    56  500 |      228.8   247.4
```

**Findings:**
The scalar variant resulted slower in every scenario

**Comment by CarlosHdezM** [comment]
## 3. Refactoring `findPathFurthestReachedPointArcLength` according to the proposed snippet

> _"Also maybe try this after validating its correct. Take it with the massive grain of salt that it comes from Claude with some human tweaks by yours truly...."_ 

@SteveMacenski I analysed and tested the snippet, thanks :) . It actually introduces an alternative approach using Eigen for the Euclidean matching part. I traced back the previous conversation mentioning that Eigen was already tried in the past for this part and was found slower; however this implementation is different and resulted faster. Here are the details:

### 3a. Why the previous Eigen-based Euclidean suggestion was slower

The history here goes through two PRs:

- A) In the discussion of **#5698**, it was proposed and tested an inner loop built the full distance matrix via `.replicate()` (let's call this Strategy A):
  ```cpp
  const auto dx = (data.path.x.transpose()).replicate(traj_x.rows(), 1).colwise() - traj_x;
  ```
  @mini-1235 measured this. It was the **slowest** option.
- B) In **#5792**, this was replaced with a scalar `for i { for j { if d < min_sq } }` loop. It was noted that this scalar version beat the Eigenized one (Let's call this strategy B).

- C) Your snippet @SteveMacenski, proposes a different approach using Eigen. Let's call it "Strategy C". 



I tested the three strategies in isolation. And the results show consistently Strategy C as the clear winner:


**Test 1 — nav2 default (batch=1000, path=100), N=100 iterations:**

| Strategy | Total | Per call |
|---|---|---|
| A (replicate+minCoeff) | ~1.3 ms | ~12.7 µs |
| B (scalar, current `main`) | ~0.7 ms | ~6.9 µs |
| **C (lazy minCoeff, this PR)** | **~0.6 ms** | **~6.4 µs** |

**Test 2 — sweep across 8 scenarios, N=500, µs per call:**

| Scenario | batch | path | A (µs) | B (µs) | C (µs) | C vs B |
|---|---|---|---|---|---|---|
| 1 | 1000 | 100 | 12.7 | 6.9 | 6.4 | −7% |
| 2 | 2000 | 140 | 30.6 | 14.6 | 11.7 | −20% |
| 3 | 2000 | 200 | 53.2 | 32.7 | 22.8 | −30% |
| 4 | 500 | 60 | 4.3 | 2.5 | 2.3 | −9% |
| 5 | 2000 | 300 | 110.1 | 74.0 | 50.3 | −32% |
| 6 | 1000 | 500 | 422.9 | 410.4 | 259.2 | −37% |
| 7 | 2000 | 60 | 9.4 | 2.5 | 2.3 | −9% |
| 8 | 500 | 500 | 209.3 | 205.5 | 129.6 | −37% |

NOTE: These tests were done only on the Euclidan-match portion, not the entire method.

### 3b. Refactor summary

Beyond the Euclidean-matching part, the rest of the refactor follows the structural suggestions, after verifying they are correct.

Conclusion: It seems that Strategy C (Eigen) is the way to go here :)
Note: I used Claude extensively for testing, of course altogether with manual verifications on my side as well.

**Comment by CarlosHdezM** [comment]
## 4. Caching `path_integrated_distances` (@adivardi)

> _"I think you should cache this. Put it in another function `computePathIntegratedArcLength` plus another `setPathIntegratedPathLengthIfNotSet`. If you check, this is the same computation done in `path_align_critic`. So if you cache it, it will only be done once."_

Hi @adivardi — I implemented the cache and ran measurements. 

**What was implemented:** I implemented the cache for `path_integrated_distances` (the cumulative arc-lengths along the reference path).  It turned out more intrusive than I initially expected:

- 2 new functions added to `utils.hpp` (`findPathIntegratedDistances`, `setPathIntegratedDistancesIfNotSet`)
- `CriticData` gains a new field: `std::optional<std::vector<float>> path_integrated_distances`
- `optimizer.hpp` in-class initializer updated
- `optimizer.cpp` `prepare()` reset updated
- `path_align_critic.cpp` refactored to use the cache
- 3 test files touched to add the new `std::nullopt` to every `CriticData` aggregate initializer — 16 sites total

At a first glance I thought `PathAlignCritic` was computing the integrated arc-length of **all the candidate trajectories**, which would be O(batch × steps) and genuinely expensive to duplicate. On closer inspection, it's only O(path_len) over the reference path — a much cheaper computation.


**Performance measurements:**

I ran two levels of benchmarking:

1. **Isolated micro-benchmark** — measuring only the two competing patterns in a tight loop. Result: the cache saves **~50–390 ns** (yes, nanoseconds) per control cycle depending on `path_len`. The saving scales linearly with `path_len` as expected.

2. **End-to-end benchmark** — measuring the full `findPathFurthestReachedPointArcLength` function (which includes the dominant O(batch × path) Euclidean inner loop) with and without the extra path sweep added on top, across all 8 typical deployment scenarios. Result: the ~50–390 ns saving is **completely invisible**, as it is within run-to-run noise of a few µs. In the end the dominant Euclidean inner loop cost is way larger.

**Conclusion:** the cache saving is real and measurable in isolation, but immeasurable in practice at the control cycle level. Given that the implementation touches 7 files and 16 aggregate initializer sites, **I'm not sure it's worth the churn** for this gain.

I have already implemented it on that branch anyway, so I'm happy to include it in the PR if indicated. I'd appreciate your opinion as well as @SteveMacenski  and @mini-1235 directions on whether this is something worth including in this PR or leaving out.

One note for future work: the interesting cache candidate Steve mentioned — `Eigen::ArrayXf integrated_traj_distances` (cumulative arc-lengths over all candidate **trajectories**, O(batch × steps)) — would be worth revisiting if multiple critics end up needing per-trajectory arc-lengths independently, but that feels like a separate PR - future work.

**Comment by CarlosHdezM** [comment]
## 5. Summary: Action Items

In general, we need to confirm/decide:

- I. Removing the `use_arc_length_path_progress` parameter -> Do you agree to proceed this way? So I can work on that
- II. Uses of "Eigen vs Scalar" on different parts-> I have tested extensively and have clear conclusions; however, I would apreaciate double-checking. Happy to accomodate and change things if needed
- III. Should we add the cache of `path_integrated_distances` or not? -> I'll proceed as indicated.
- IV. After confirming on the above, I will add the corresponding unit test coverage :) 

Please give me a heads up, and I'll proceed with whatever is missing to get this done ;)

**Comment by adivardi** [comment]
> 2\. **End-to-end benchmark** — measuring the full `findPathFurthestReachedPointArcLength` function (which includes the dominant O(batch × path) Euclidean inner loop) with and without the extra path sweep added on top, across all 8 typical deployment scenarios. Result: the ~50–390 ns saving is **completely invisible**, as it is within run-to-run noise of a few µs. In the end the dominant Euclidean inner loop cost is way larger.

you are probably right, but just as a sanity check, what was the `prune_distance` you used?

**Comment by CarlosHdezM** [comment]
> you are probably right, but just as a sanity check, what was the `prune_distance` you used?

I benchmarked with point spacing of 0.05m between path points, from 60 points to 500 pts, `prune_distances` from 3.0m to 25.0m (most likely unrealistic to be this high, but good to know for benchmarking). The ~50–390 ns optimisation scales linearly with the length, of course:

| `prune_distance` | saving due to cache |
| --- | --- | 
| 3.0m | 50 ns |
| 25.0m | 390 ns |

**Comment by SteveMacenski** [comment]
@CarlosHdezM just a friendly reminder, it would be good to talk to maintainer and not post the outputs of AI models. It makes me think I'm talking to an AI and not you as a developer summarizing your thoughts, testing, results (and makes me wonder if some of the metrics are real or assumed or hallucinated from AI generating information). These 5 point posts are alot of reading and delays meaningful reviews from maintainers to crawl in detail through all that information. You should distill it to final thoughts, test metric results from evaluation, and your recommendations, not a blow by blow :-) **But it should be distilled from your actual personal thoughts and experiences and analysis, not AI**. Its not super respectful of our time.

Can you please verify that the quantities in the table for my method were from actual experiments you measured and not from AI? Also that you tested your general solution (and this final one with option "C") with real plans in simulation and see that it has good, rational behavior? I still don't see the "ON" video :wink: 

> Serpentines (adjacent parallel segments): @adivardi confirmed the fix eliminates the jump to the next serpentine line ✓

This makes me think perhaps you didn't and its just the AI model saying you did. This is clearly claude.

---

> Result: the ~50–390 ns saving is completely invisible, as it is within run-to-run noise of a few µs. In the end the dominant Euclidean inner loop cost is way larger.

Agreed, dont do this. Its not worth that tiny change.

> Conclusion: the cache saving is real and measurable in isolation, but immeasurable in practice at the control cycle level

.... Again, this makes me very suspicious about your conclusions and numbers, that's not what the AI even says right above. 

> Result: the cache saves ~50–390 ns (yes, nanoseconds) per control cycle 

These numbers are the exact same and are still meaninglessly small. 

I'm giving you the benefit of the doubt that you actually did these experiments yourself, but I would like you to specifically tell me that is true and you have tested the performance, behavior and validate to me that this is true. When I go to test this PR's changes myself and I start seeing garbage or vastly different performance, I may be tempted to close this PR as `wontfix` since I can't trust what I'm reading, even if it is a real problem. 

Deal? :wink: 

---

> I. Removing the use_arc_length_path_progress parameter -> Do you agree to proceed this way? So I can work on that

Yes :-)

**Comment by CarlosHdezM** [comment]
> I'm giving you the benefit of the doubt that you actually did these experiments yourself, but I would like you to specifically tell me that is true and you have tested the performance, behavior and validate to me that this is true. When I go to test this PR's changes myself and I start seeing garbage or vastly different performance, I may be tempted to close this PR as `wontfix` since I can't trust what I'm reading, even if it is a real problem.


Hi @SteveMacenski. Thanks so much for taking the time to review the loooong messages. I really appreciate it. Indeed, you're talking to a human who has been working on this.
For all my previous messages. I spent the two past weekends and the past week after work working on this PR: collecting data, running experiments and benchmarks, taking my notes, creating my own conclusions based on data and observations. Human data and conclusions, not AI. I ended with HUGE documents, outputs and notes (yes, if the 5 points are long, my original notes,  thoughts, testing, results were massively longer and more verbose :/ ).

I then used a model to summarize, check for grammar (and language correction as well, as English is not my first language). However, always checking in detail that the corrected version exactly adjusts to what I'm trying to say (and cut the redundantness/imprecissions of my redactions).  So, the "5 points" are not "hallucinations" but the result of what I've been working on. In general I used Claude but to generate paths for testing, and generate some test cases, some quick prototypes as well, but always and every time verifying myself. 

My apologies that the final redaction indeed heavily "touched" by AI (but from my own conclusions, etc) suggested that all of this is just "AI slop" :(  I can assure you that it's not. I have been working thorougly myself on it; and I do agree with you that if it was the case that this is only AI outputs it would be super disrespectful towards you. I just want to reassure you that it is not the case. so yes, addressing your question, I can specifically confirm it. Again, I'm sorry.

Also, noted. I will be way briefer in the future. I agree that it's too long. I didn't want to leave details out and I tried to address everything in the 5 points, but I agree that it delays reviews from mantainers.

In any case, my proposal is the following:
I will work on consolidating the conclusions and final implementation based on your comments, and I will add test coverage as well. I will push to this PR and let you know once it is done. You can then test it, and I can assure you that you won't get "garbage" or "poor performance", but of course if that was the case, of course let's close it; but you wont, I wouldn't make such a disrepectful use of your time. I need some days, though, as I can only work on it after work :)  

So once its done, I can confirm. 
@SteveMacenski sounds like a plan? :) 

Note:
>I still don't see the "ON" video 😉

I actually added the "ON" videos on Apr 9 but as an "edit" instead of a new message, so they are up in the thread. Sorry for the confusion :)

**Comment by SteveMacenski** [comment]
> My apologies that the final redaction indeed heavily "touched" by AI (but from my own conclusions, etc) suggested that all of this is just "AI slop" :( I can assure you that it's not.

Hey - I appreciate that. I got the sense that you were probably doing the right thing, but overly copy+pasted outputs back to here. I felt like I was reading some of your words interwoven with the AI, so it wasn't just a case of AI slop, which is why I gave you the benefit of the doubt to read it all in detail. Fixing english mistakes is actually a really good use of it - but maybe just have it do corrections and not expand on it in its own words.

I appreciate your work / responsiveness / open for discussion, but just letting you know how it seems when you put in large blocks of AI generated text. No worries from me - live and learn :-) 

I'd recommend either communicating based on what you read in your summaries in your own words (+ metrics) or very clearly marking in responses what's you and you're just showing me about what Claude said about it (but not reading it like 'this is the truth'). But in general paring it down - I don't need to hear about 'why its slower' for instance, just that you tested a few formulations and I was correct that leveraging SIMD was faster and you made that respective change. I know why I think it should be faster :wink: 

Let me know when you're ready!

**Comment by CarlosHdezM** [comment]
Hi @SteveMacenski, it's finally ready and simplified a lot :)
I'll try to be brief:

### 1. Params removed
The param added before was removed, not needed at all as discussed before

### 2. Limit the Euclidean search to what is feasibly achievable
The initial implementation of this PR was: "if the euclidean match is larger than what is physically achievable by the candidate trajectory, then cap the index to the maximum achievable distance".  That's what the max(min(euclidean,arc_len) was doing. But we can do better.

Slight refinement introduced: instead, the method now directly performs the Euclidean search within what is physically achievable by the candidate trajectory only. The change is subtle but meaningful: it has a stronger physical meaning and is not a "fallback" anymore. It's also slightly cheaper to compute, as the euclidean match is computed only in the portion that makes sense. 

By the way, as I know it could be a concern:  I also verified that the method doesn't unexpectedly underestimate and it doesn't.

### 3. Final benchmarks
It seems that the arc-length computation overhead is "balanced out" by the Eigenized operations and the optimization in the region to search. Performance-wise, these are the results I obtained with the "old" (the one currently in main) and the one proposed in this PR. So if everything makes sense, basically overall the change comes for free :) 

One of the benchmarks I used is in this other branch: [benchmark branch](https://github.com/CarlosHdezM/navigation2/tree/testing/benchmark-find-path-furthest), particularly [this commit](https://github.com/CarlosHdezM/navigation2/commit/2a7f40551d6cb4299d512870a7f377d149048cb8), for verifications and replication purposes.
@mini-1235, I believe you have benchmarked this method in the past. In case you have the chance, I would really appreciate it if you could take a look. 

| batch - time steps - prune distance | OLD (µs) | NEW (µs) | 
|---|---|---|
| 1000/56/2.0m | 61.5 | 58.7 |
| 2000/56/2.0m | 123 | 119 | 
| 1000/80/3.0m | 87.8 | 84.5 |
| 2000/80/3.0m | 177 | 171 | 
| 1000/80/5.0m | 155 | 153 | 
| 2000/80/5.0m | 314 | 315 |

### 4. Coverage
I  added a new test. As suggested @SteveMacenski, it verifies that `findPathFurthestReachedPoint` doesn't select the "wrong leg" on the u-turn reference path of the test (it actually tests that the index returned by the method is not larger than the length of the trajectory, which is physically sound and it should be forward-compatible with future improvements in this method).

**Comment by SteveMacenski** [comment]
@mini-1235 can you take a look/test? I generally agree the code is sane, but want your opinion. 

I would just like to rename things: `path_arc` `traj_arcs` to `path_integrated_dists` and `traj_integrated_dists`  as more descriptive to what they are.

I'd love to get this in before Lyrical!

**Comment by CarlosHdezM** [comment]
> I would just like to rename things: `path_arc` `traj_arcs` to `path_integrated_dists` and `traj_integrated_dists` as more descriptive to what they are.

Variables renamed as suggested :)

**Comment by CarlosHdezM** [comment]
It seems like circleci is failing. I'm rebasing and force-pushing and hopefully it will suceed this time, as I won't have my computer for some days.

**Review by mini-1235 — APPROVED** [review]
I tested this locally and looks good to me!

**Comment by CarlosHdezM** [comment]
> I tested this locally and looks good to me!

@mini-1235 
Thanks for taking the time to test!
Also after the rebase now everything is passing correctly :)

**Comment by SteveMacenski** [comment]
@tonynajjar can you or Nelson sanity check this for your testing purposes? I'm happy with this, as well as Maurice, and Carlos. You're my last sanity check since this is a subtle change. 

Basically it uses integrated distances rather than L2 distances for finding the furthest path point so sharp turns and U turns don't "jump" as much to track the path better.

**Comment by tonynajjar** [comment]
Yeah sometime next week

**Comment by SteveMacenski** [comment]
@CarlosHdezM follow up with us at the end of next week if you don't hear from us before :-) 

Thanks for your great work here and would love your help in other MPPI or Nav2 issues as you have bandwidth/desire! Its been a pleasure.

**Comment by CarlosHdezM** [comment]
@SteveMacenski Great! Thanks a lot. It's been a pleasure.
Of course I'll keep contributing to MPPI / Nav2 in general ;)

**Comment by tonynajjar** [comment]
The logic looks sane. I don't have such U-turns so I can't really test the upsides of this PR but I think you took care of that already. I was rather making sure that it doesn't break any of my existing behaviors and I can confirm nothing breaks so happy to get that in :+1:

**Review by SteveMacenski — APPROVED** [review]
Great! Approved, tested, and now shipped 😉

**Comment by CarlosHdezM** [comment]
@SteveMacenski  Great, thanks a lot!
This is a feature I would really like to have backported to Jazzy (as jazzy is actually my target), so I wanted to ask you:

* Is backporting this to Jazzy something we can consider?
* How would it work? Should I open a separate PR for that? 

I'm not quite aware of what's the converntion here

**Comment by SteveMacenski** [comment]
Yes, this can be backported into the jazzy distribution. However, I think we should give a few weeks of soaking time to identify any potential issues before we do so. Can you open up a PR in ~3 weeks cherry picking this commit to Jazzy?
