### PR TITLE
Fix ConstraintCritic to enforce axis-wise velocity bounds for holonomic robots

### LINKED ISSUE #6042: MPPI: Velocity constraint inconsistency: vx_min violated but no cost applied in ConstraintCritic
I have a question regarding the design of ConstraintCritic velocity bounds for holonomic robots.
[https://github.com/ros-navigation/navigation2/blob/554e0ff999933dca6c4243ad94e08f4438388a9f/nav2_mppi_controller/src/critics/constraint_critic.cpp#L38-L39](https://github.com/ros-navigation/navigation2/blob/554e0ff999933dca6c4243ad94e08f4438388a9f/nav2_mppi_controller/src/critics/constraint_critic.cpp#L38-L39)
Given:
vx_max = 0.5
vx_min = -0.3
vy_max = 0.5

The critic computes:
max_vel = sqrt(vx_max^2 + vy_max^2) ≈ 0.707
min_vel = -sqrt(vx_min^2 + vy_max^2) ≈ -0.583

Now consider a trajectory:
vx = -0.4, vy = 0 → v = -0.4

This satisfies:
v ∈ [min_vel, max_vel] → no cost applied

However:
vx = -0.4 < vx_min = -0.3 → violates longitudinal constraint

This suggests that the critic enforces a magnitude-based constraint
rather than axis-wise bounds, allowing physically invalid velocities
(along vx) to pass without penalty.

Is this behavior intentional for smoothing / MPPI optimization reasons,
or is it an oversight?
Thanks

### PR DESCRIPTION
**Pull request by prajwalthakur**
Use axis-wise velocity constraints (vx, vy) in ConstraintCritic instead of magnitude-based bounds for holonomic robots.
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  closes #6042 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on |  / |
| Does this PR contain AI generated software? |  No |
| Was this PR description generated by AI software? | Out of respect for maintainers, AI for human-to-human communications are banned |

---

## Description of contribution in a few bullet points

* Updated ConstraintCritic score function for holonomic robots to use axis-wise velocity constraints (vx, vy) instead of magnitude-based checks.

## Description of how this change was tested

* Added unit test for holonomic robot in CriticTests.ConstraintsCritic

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists
- [ ] Should this be backported to current distributions? If so, tag with `backport-*`.

### CODE REVIEW

File: nav2_mppi_controller/src/critics/constraint_critic.cpp [hunk 1]
```diff
@@ -34,6 +34,9 @@ void ConstraintCritic::initialize()
   getParentParam(vx_min, "vx_min", -0.35f);
 
   const float min_sgn = vx_min > 0.0f ? 1.0f : -1.0f;
+  vx_max_ = vx_max;
+  vx_min_ = vx_min;
+  vy_max_ = vy_max;
   max_vel_ = sqrtf(vx_max * vx_max + vy_max * vy_max);
   min_vel_ = min_sgn * sqrtf(vx_min * vx_min + vy_max * vy_max);
```
Comment (SteveMacenski) [inline nav2_mppi_controller/src/critics/constraint_critic.cpp]: Can these be removed? Its only used in ackermann / diff drive which can simply use `vx_max` since it cannot have any Vy

File: nav2_mppi_controller/src/critics/constraint_critic.cpp [hunk 2]
```diff
@@ -58,21 +61,20 @@ void ConstraintCritic::score(CriticData & data)
...
-
-    auto vel_total = sgn * (data.state.vx.square() + data.state.vy.square()).sqrt();
-    if (power_ > 1u) {
-      data.costs += ((((vel_total - max_vel_).max(0.0f) + (min_vel_ - vel_total).
-        max(0.0f)) * data.model_dt).rowwise().sum().eval() * weight_).pow(power_).eval();
+    auto & vy = data.state.vy;
+    auto vx_violation = (vx - vx_max_).max(0.0f) + (vx_min_ - vx).max(0.0f);
+    auto vy_violation = (vy.abs() - vy_max_).max(0.0f);
+    auto violation = ((vx_violation + vy_violation) * data.model_dt).rowwise().sum().eval();
+    auto weighted_violation = violation * weight_;
```
Comment (SteveMacenski) [inline nav2_mppi_controller/src/critics/constraint_critic.cpp]: Stylistically we do this in the if/else conditionals inline the `data.costs += ...`. You don't have to do that here, but you should at least update the others to be consistent. Or, change yours here.

If you decide to change them all, please make sure with some quick benchmarking there's not a measurable performance difference.

**Review by SteveMacenski — COMMENTED** [review]
Please also indicate how you tested this and validated its helpfulness / correctness

But in general, looks good :smile:

File: nav2_mppi_controller/src/critics/constraint_critic.cpp (hunk 1 above)
Comment (prajwalthakur) [reply nav2_mppi_controller/src/critics/constraint_critic.cpp]: yes, I have removed it now.

File: nav2_mppi_controller/src/critics/constraint_critic.cpp (hunk 2 above)
Comment (prajwalthakur) [reply nav2_mppi_controller/src/critics/constraint_critic.cpp]: I’ll run a quick benchmark to compare both approaches. If there’s no measurable performance difference, I propose keeping the refactored version for better readability and consistency.

**Comment by prajwalthakur** [comment]
> Please also indicate how you tested this and validated its helpfulness / correctness
Thanks for the suggestion. For validation, I was thinking to compare (do it seperately and not to include in the tests script ) the critic cost before and after the change in a case like I mentioned in #6042 might be sufficient?

File: nav2_mppi_controller/src/critics/constraint_critic.cpp (hunk 2 above)
Comment (SteveMacenski) [reply nav2_mppi_controller/src/critics/constraint_critic.cpp]: OK! Otherwise this is approved, I just want there to be code consistency. I don't expect there to really be a difference but sometimes compilers do weird shit and this is one of the few places in Nav2 that smal changes really do matter.

File: nav2_mppi_controller/test/critics_tests.cpp [hunk 3]
```diff
@@ -125,6 +125,70 @@ TEST(CriticTests, ConstraintsCritic)
...
+  state.vy.row(999).setConstant(-0.5f);
+  critic.score(data);
+  EXPECT_GT(costs.sum(), 0);
+  // vx-violation 4.0 weight * 0.1 model_dt * 0.1 error introduced * 30 timesteps = 1.2
+  // vy-violation 4.0 weight * 0.1 model_dt * 0.2 error introduced * 30 timesteps = 2.4
+  // total-violation = 1.2 + 2.4
+  EXPECT_NEAR(costs(999), 3.6, 0.01);
+  costs.setZero();
+
+  // TODO(prajwalthakur): not able to set the power greater than 1u
```
Comment (SteveMacenski) [inline nav2_mppi_controller/test/critics_tests.cpp]: TODO

**Comment by SteveMacenski** [comment]
Yeah that would be good -- your unit tests should already just check in general that they penalize things correctly for each axis, so if you just throw in a real world example for your platform where it would have failed before and show the penalties are higher where violating the constraint than before, I think that's enough for me.

Ultimately I think you should test this on your robot and make sure you see improved behavior. If you have done that already / plan to + the unit tests, that's good enough for me.

File: nav2_mppi_controller/src/critics/constraint_critic.cpp [hunk 4]
```diff
@@ -33,9 +33,9 @@ void ConstraintCritic::initialize()
   getParentParam(vy_max, "vy_max", 0.0f);
   getParentParam(vx_min, "vx_min", -0.35f);
 
-  const float min_sgn = vx_min > 0.0f ? 1.0f : -1.0f;
-  max_vel_ = sqrtf(vx_max * vx_max + vy_max * vy_max);
-  min_vel_ = min_sgn * sqrtf(vx_min * vx_min + vy_max * vy_max);
+  vx_max_ = vx_max;
+  vx_min_ = vx_min;
+  vy_max_ = vy_max;
```
Comment (mini-1235) [inline nav2_mppi_controller/src/critics/constraint_critic.cpp]: You can directly use the member variable, I think.
```suggestion
getParentParam(vx_max_, "vx_max", 0.5f);
getParentParam(vy_max_, "vy_max", 0.0f);
getParentParam(vx_min_, "vx_min", -0.35f);
```

Sorry the suggestion block is not working well here

**Comment by SteveMacenski** [comment]
@prajwalthakur the ROS 2 Lyrical freeze is rapidly approaching and I want this included in the release. Can you get these last points addressed so we can merge this in? Thanks! 

I think all you need to do is check the compute time and make sure its in-line & update the tests and this is ready

File: nav2_mppi_controller/src/critics/constraint_critic.cpp (hunk 2 above)
Comment (prajwalthakur) [reply nav2_mppi_controller/src/critics/constraint_critic.cpp]: I reverted it back, to match the code consitency. (its inline now ) . Didnt get much time to run the benchmark.

File: nav2_mppi_controller/src/critics/constraint_critic.cpp (hunk 4 above)
Comment (prajwalthakur) [reply nav2_mppi_controller/src/critics/constraint_critic.cpp]: Thanks, made changes.

File: nav2_mppi_controller/test/critics_tests.cpp (hunk 3 above)
Comment (prajwalthakur) [reply nav2_mppi_controller/test/critics_tests.cpp]: I am still not able to set the cost_power, because of that code coverage is not 100%. Do you have any idea what could be the issue ?

File: nav2_mppi_controller/src/critics/constraint_critic.cpp [hunk 5]
```diff
@@ -48,31 +43,29 @@ void ConstraintCritic::score(CriticData & data)
...
     } else {
-      data.costs += (((((data.state.vx - max_vel_).max(0.0f) + (min_vel_ - data.state.vx).
+      data.costs += (((((data.state.vx - vx_max_).max(0.0f) + (vx_min_ - data.state.vx).
         max(0.0f)) * data.model_dt).rowwise().sum().eval()) * weight_).eval();
     }
     return;
   }
 
   // Omnidirectional motion model
+  // Axis wise violation check
```
Comment (SteveMacenski) [inline nav2_mppi_controller/src/critics/constraint_critic.cpp:56]:
```suggestion
// Omnidirectional motion model - Axis wise violation check
```

File: nav2_mppi_controller/test/critics_tests.cpp (hunk 3 above)
Comment (SteveMacenski) [reply nav2_mppi_controller/test/critics_tests.cpp]: What's the problem?

**Review by SteveMacenski — COMMENTED** [review]
Just need to deal wit hthe test TODOs, otherwise approved

File: nav2_mppi_controller/test/critics_tests.cpp [hunk 6]
```diff
@@ -125,6 +125,68 @@ TEST(CriticTests, ConstraintsCritic)
...
+  // power > 1u
+  // node->declare_parameter("mppi.critic.cost_power", 2);
```
Comment (prajwalthakur) [inline nav2_mppi_controller/test/critics_tests.cpp]: I was expecting that this would change the cost_power parameter, and hence the next two lines would initialize the ConstraintCritic() with power_  = 2. But `EXPECT_NEAR(critic.getPower(), 2, 1e-6)` still failiing and showing that critic.getPower() is still 1.

File: nav2_mppi_controller/test/critics_tests.cpp (hunk 3 above)
Comment (prajwalthakur) [reply nav2_mppi_controller/test/critics_tests.cpp]: see comment for the the line `node->declare_parameter("mppi.critic.cost_power", 2);`

File: nav2_mppi_controller/test/critics_tests.cpp (hunk 6 above)
Comment (SteveMacenski) [reply nav2_mppi_controller/test/critics_tests.cpp]: Just ignore the non-1 power for right now, that's not a gap you created. I just want to know that your contributions on the per-axis constraints are working properly with analytical results :-)

**Comment by SteveMacenski** [comment]
@prajwalthakur ready to merge? Can you make this no longer a draft?

File: nav2_mppi_controller/include/nav2_mppi_controller/critics/constraint_critic.hpp [hunk 7]
```diff
@@ -40,15 +40,17 @@ class ConstraintCritic : public CriticFunction
    * @param costs [out] add reference cost values to this tensor
    */
   void score(CriticData & data) override;
-
-  float getMaxVelConstraint() {return max_vel_;}
-  float getMinVelConstraint() {return min_vel_;}
+  float getMaxVelXConstraint() {return vx_max_;}
+  float getMinVelXConstraint() {return vx_min_;}
+  float getMaxVelYConstraint() {return vy_max_;}
+  unsigned int getPower() {return power_;}
```
Comment (mini-1235) [inline nav2_mppi_controller/include/nav2_mppi_controller/critics/constraint_critic.hpp]: Where is this used? I think this should be removed

**Comment by mini-1235** [comment]
I removed the dead code and added more tests for code coverage, I think this should be good to go now!

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Thank you - thank you all. Glad to have this in before Lyrical!
